name: whatru
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  app_settings: ^7.0.0
  cloud_firestore: ^6.2.0
  cloud_functions: ^6.1.0
  file_picker: ^10.3.10
  firebase_auth: ^6.3.0
  firebase_core: ^4.6.0
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.5
  url_launcher: ^6.3.2
  http: ^1.2.0
  cached_network_image: ^3.3.0
  flutter_markdown: ^0.7.7+1
  crypto: ^3.0.3
  archive: ^3.4.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

flutter_native_splash:
  color: "#080B0E" 
  image: "assets/icon/app_icon.png" 
  android_12:
    image: "assets/icon/app_icon.png"
    color: "#080B0E"