// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQ7knXg0GmzvtdMREqdx45O4ZtUnxVtDI',
    appId: '1:698859664357:web:52bedf4f66693b3567350c',
    messagingSenderId: '698859664357',
    projectId: 'whatru-security',
    authDomain: 'whatru-security.firebaseapp.com',
    storageBucket: 'whatru-security.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoy5Ow3oZbnY_map7dOV9DHDD8F7ztPLA',
    appId: '1:698859664357:android:0bf2574d2d47d53967350c',
    messagingSenderId: '698859664357',
    projectId: 'whatru-security',
    storageBucket: 'whatru-security.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvM_TnmLfBijW5laOmu_aIoAFkeQvGZtk',
    appId: '1:698859664357:ios:a134adf78b9e6cc767350c',
    messagingSenderId: '698859664357',
    projectId: 'whatru-security',
    storageBucket: 'whatru-security.firebasestorage.app',
    iosBundleId: 'com.example.whatru',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvM_TnmLfBijW5laOmu_aIoAFkeQvGZtk',
    appId: '1:698859664357:ios:a134adf78b9e6cc767350c',
    messagingSenderId: '698859664357',
    projectId: 'whatru-security',
    storageBucket: 'whatru-security.firebasestorage.app',
    iosBundleId: 'com.example.whatru',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQ7knXg0GmzvtdMREqdx45O4ZtUnxVtDI',
    appId: '1:698859664357:web:541f22bbe45dd03167350c',
    messagingSenderId: '698859664357',
    projectId: 'whatru-security',
    authDomain: 'whatru-security.firebaseapp.com',
    storageBucket: 'whatru-security.firebasestorage.app',
  );
}
